apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: nextcloud-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./postgres-secret.sops.yaml
  - ./config-secret.sops.yaml
