apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - nextcloud-pvcs.yaml
  - nextcloud-deployment.yaml
  - nextcloud-service.yaml
  - nextcloud-ingress.yaml

generators:
  - ksops-generator.yaml
