#ENC[AES256_GCM,data:jxqGcMbKHsV2BKR9pQa37xzWnMMtWA5gcDOtgB/+T1vFHOYhaghPo+2m4onmddVFqyCkurJ3TuZkDv6uYYGr/rYUQ7j1PTxQIDh1,iv:pFW4YxAkWFkN+SGbKz4fIysJPFum9oB+AGXdwTIQeCE=,tag:agUwfCYSwXf1Ryyo/iJvxA==,type:comment]
#ENC[AES256_GCM,data:CLaYMjkh9H/nSXcYrkYR2sRtkJ2+8qgMNDC2HOfdu94VhfiArmnYqZeAfVxwOAsehLzoW90LD5Z4M/kzg7V5uwBx6cw=,iv:Fq0t2VKbEiHR3SZFfVX5d39F5UfxnTdbsjqbHVq97gY=,tag:YbpeaS2BXf1G5qxw6RtuWg==,type:comment]
#ENC[AES256_GCM,data:40pO3p2HRQtmzfIfLS6y1hHnHlO7cbKYQ8xcgm1M030DjGm1YSo=,iv:kHiYuerYp5nILgOm7Q1Wumb+1yPrpvnmviWxmHQBb5g=,tag:wjxoTXO4pKAEVitlLlnYfg==,type:comment]
apiVersion: ENC[AES256_GCM,data:F4A=,iv:06hcpheFOcfNaKZ43bsuBiHYdwTkuUoXRHOHvrRCwL4=,tag:DDm3P57eleG1jNrQyIDSpQ==,type:str]
kind: ENC[AES256_GCM,data:43Ua2jcK,iv:gcMJ6qbCIesWu+wufzCoRZv+I8Ri5ZiLEjZUA/fXM/M=,tag:xQFjlIdjPM3gwQBgyrRJ/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nz682SaX/DjZ7IdHpfGTqoYP57A=,iv:r/beyqgT9srFDdBRYc74UxLYlfDi+5F+maluK00OUS8=,tag:5lenXwbXqnpp+Mf/24tGuw==,type:str]
    namespace: ENC[AES256_GCM,data:7fEGDQFdkn6b,iv:/hmQuBJEOceM/tSv2fZaZeG0cvohqpljokPBtGDgEj4=,tag:HoF978/8WWtVF5TGON1TIQ==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:fPx93VdGoSK4,iv:KHu8H064l9+TfpUheCdY/JpenClsV0TOWjz+9H2kYLw=,tag:3lZs8SMNBoANL27IiSzpzw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:E3IsYDPDv5j5,iv:wbVp5rlofgH12jFWFol0aoRpuz8TqnlweogLMfVYZz4=,tag:uaNKbqMH+mEPs36A2qNIog==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3il9755yZd5N0colfeE=,iv:SzSPR7frxKebzh28rRY8He85FF/l+PwiTzgL5nMye7Y=,tag:YHkWCitHLkla7QnjoH3h6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWlFsQURlT0ZkQnRBUWpl
            Ri9Pc0VYbm04RVZZTkRkMG1KMUp2SGhxTTNzClF2Y2Rpekg3czk0bW9ia3llQmRh
            c3IzMTBNWjBZZkFNbHlUTWxrdzNabUEKLS0tIGJuMWt6S1BqZmxpVW1wTmY2a1hZ
            dGx2ZHpVbkt0cHB0WkVDcGpVQ0o5eFUKag5ur1LwGaa+Ny2WpnyVdC9EJWSDWbgB
            yxd0nPxzBcypWc+6LU72rZHAUyHTCx9tfdY++p8W7uBQ8WST08I4XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-02T20:50:58Z"
    mac: ENC[AES256_GCM,data:T8wjzXcRJcvxAEfH/RLKhhAPtMgsL10JgfAmux7VNePXc9rtnN2woKT+oHrLjCe1apr6ALIcZ50BoRjyKrwSbmtacn3inSjz/mOrtY1qzGvM9EIgFbyUhjhU4/xRMAqk+mZN1TeUKSntycJ85TcC+E74wkkoewpEvirqPN9xFpE=,iv:DzujS+5jt+Sl30MaeTQGPSWTArcpQgApGNVbO+w/Gww=,tag:yZxGK7zjzHv+eJJ5i3bGdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
