apiVersion: ENC[AES256_GCM,data:a5I=,iv:jB/wbFY8qTYFvI2PiVW5toE520SCjYiVoG5aYeDT4vI=,tag:oUyhZ7osZwyOvWxCOZuuKg==,type:str]
kind: ENC[AES256_GCM,data:E/4eNpGS,iv:xsq066jEm4iY4NOh0epVwXSpQvaKEPIznh8X049V8iY=,tag:ZcA0MJXgrujUJnLG13vgoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bX2G1D8uwv7rsa3eZeM=,iv:vwOx+mD2CwtzHmOgaqO5dosMLqgsywGHbZlJoNaAiv4=,tag:uSMNQnLDw+pAN6s1MpN8zg==,type:str]
    namespace: ENC[AES256_GCM,data:Ve/9ByY=,iv:7w2MkcuEXfc+5U5TYaW30qQr+IbNQFsM+XzT1c5O17w=,tag:R5skomExPfocImlzPGnpVQ==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:P/z8COY=,iv:Uvo0MVBalDp+nGjJWXbDUoxwkU5gB9xcVPBLLekCLGE=,tag:xRVmzIO5a37ux+gVtusXJg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XSJt21OyDtrSUnbGTQexEZyPTwVe2Hy1q3E0VIZ23wI=,iv:94lJWdrWfrlJ04eeGlWTjTGXBt+FbiMlI1QBWpHMWqo=,tag:n5V/vE60FU0OUL/Pgo9AQw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:3uU0d0I=,iv:tVG/MjTx8XwOdsado/fTup5BzNntMrePF2cmtVvSvcs=,tag:mXyTW+sgnMvxWpknfoS/9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cTljRmNGVEljbUZiZ3pw
            dTllclFhdm12TitFSGNQVlltcEo1aDU3cmw0CnZmd3JJMmNqRE51d21yMU1HK0NG
            TFJ1VnZ5U2R1bFBhRmdSNUNwTVR3eFUKLS0tIDNzVWpxTnN5ZXJpMllIdVFKWXJC
            QjFJZFJUdVhJaUJ2eENWa3hYZ0d5NnMKi8epWMb9xh/eiZkujmvIixB7b3XaGMxd
            G/nHikeeA7CKhPIjBH12MJpn2mAhDYx5Lm/xT2OS3x3PZKCS7oVQsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T14:04:49Z"
    mac: ENC[AES256_GCM,data:JHc3y34yKqaK3LXmqm5mkhFgIz0R2KDSNevalXRFdkGIASFaXDuEj77DK3W+hw4NgFf7EOTsePjPuf53MgROVSjpQOfEpxLzXmQcaKdFq1CH5dtgTKR2ymbrkefQyDEXSRCF/DwXVsHHIuJh7zSXB4q0mmPKYTVDSFxcGrZ3Jzo=,iv:7GUG3rWavsFO6N3vS3aB14hH2Xj8fVMUdwii4KlA4VM=,tag:PE8Q/qqMFsXBDjKMqMpkhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
