apiVersion: ENC[AES256_GCM,data:VrQ=,iv:X7Db5TpTmPMOBn5zAt663/zR2ko/1Wc/xlGKFCYGisQ=,tag:P2LUg3IkAngufgUe9QSTaQ==,type:str]
kind: ENC[AES256_GCM,data:J/p4iSXw,iv:0VnGLsjXI1nSKOJvEASxZz+FtzXJHf11IzOrtCZWPvE=,tag:5WQS///5T9zFF8Db/K+6vA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1Qv43mKH0q7+NIaR5lc=,iv:/XxpJcaXNVFn2sVblKI+GQcelQyZ20oduiVt6KEdJcY=,tag:zO+LIHOulY2KRDMTyExDGg==,type:str]
    namespace: ENC[AES256_GCM,data:Ed0f9Gw=,iv:BXL7L9M+lYiV6hEOL5gj/A9VVaKkatqvxH3kVIdaTBo=,tag:hTRre4fakX2Dx/+DenQ84w==,type:str]
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:O73mD338hdvbDtZELSuulRU69SCn4+Ur8dU7rxZUk4Gh6Cn6CwirVTZMG9mdsA==,iv:Oq5DfjqDtyuozV4L0+WEPShzhuSZSHglT2FhzDAD6Ww=,tag:xgsSMd3czBl4PF8Y/Lf58A==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:5ziar2pqAA2vLg==,iv:7hFbJNI6OT2IwNq7R6/JYF/DG4b0xfVHm6PFadREpZQ=,tag:uegy4FliHTApnsTuq5jINQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYm1HMjkzTzZoRSs0VS9N
            aFpDUHVCSmRWSXZtcGhlcWRMSXdyeXRHOGl3CklScWZJTDZHOWVUVFFQa2FHamNX
            WDQ1WjQyeExEV0RZZExoV1NLNlhqZ3cKLS0tIFZyYVZzRWM4ZjgrZkRyMzc5dkp4
            RERYSlAwUUdvRzR3dmVyS0Nlblk4QnMK0BZCQXsvotOYAcEO+YxV/g9/0W8lZqbp
            d2PuzAPTyIhe15UUw0J89A2jpvBpqq06PYlC0sUzzQnKRVpFUL0Lkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T14:17:46Z"
    mac: ENC[AES256_GCM,data:qPmXiqZXIq7tDOF0r8dOrzMZ3hD5zcmyZIUpdPvb4PsZdI6C04UtX3aVtOzwjd0Njrl98FWHtTOrxO7Kk1HFf2d4xVYK75gdF0rniiCSn/qu5GziWhLIj7769s6ZeQADkt3EnU3TZ7CAouA4f1Nos3S9wH6mYEu7dHnJIrhJIpQ=,iv:OrqD2G0Ux1Q1Bzm/UhRTTMqZDscjUcncH+ojEgYKUog=,tag:iwGUkAbf19toiVX6RXjLGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
