apiVersion: ENC[AES256_GCM,data:xNA=,iv:1DVoOGrYRUT0+uOYBhaAxJVBz9sMwtyK5qRm840RGPY=,tag:kO/u/O3Hn8Brv/918JGFIg==,type:str]
kind: ENC[AES256_GCM,data:vYi/poGn,iv:qzTixrgxu5EiLucvYUF2FR4N/wIqlrgWqkaaCn1ATDE=,tag:/i700NIpeKZoN2Cagxf7EA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I2etOp53da7Pdlu5fVI=,iv:SwA+dP40ssq+ZmUDeMp/FrA7WVr+G4qODb7UbYJZLjA=,tag:dnvynY9k1Y7m179Wl2mT8Q==,type:str]
    namespace: ENC[AES256_GCM,data:FBDzUWA=,iv:80vKfqFCD41oyxll+FafhnS8Cqdm6U4mcSjxNjwvNoQ=,tag:dkokeBnFXe7T/UEFYG9plQ==,type:str]
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:JQh7Y9frTZbtFA==,iv:li2j/2R3KMrByDfpwQQBnC/dh2kLgeTnY4buBkrSmow=,tag:r1WR+uwCwPXocTLxSpgldw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:Ip7fLn71Acy7UA==,iv:e2WjTFSFfDI0NVqy328dbcON9GqvdDUCrLBuaqsarSo=,tag:HQ6sfV/l+myoRULRFMahRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRkUxY3k5VmdURjVoUXZR
            enQxcGE1eFYyVDlEWjl3c3pQZ0t5ZUFiaW5vCm52OGZSS0plbWhYaXZGZmJmS0dN
            Mjl5eHo5ZDR5aWpWdUxQamlQcnREV0EKLS0tIFFaN3dTeW9GMmFGd0FwTjlKRjRa
            V2lZYnRTbndZZzIzTXVkL0RDMTJKZVEKlnkG7QLmjDOYJMfg1adGBUHlufiPa4uC
            U+aovGF0lvvfdyNxZ/VLxqIo20epAbqEAIIot0BQj0DFoflFq85O8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T14:07:31Z"
    mac: ENC[AES256_GCM,data:b8jsesJRY96hN5wBvcWU1JnYX3U50KV09gmWZvwwmyulGXrXwTaUpXRRzBPfAQ48ZJwRYiO8ZGb7Fuu7mHeduNG/crx/d8Qv0fRQSrH1BQSlqdLdClNxvZju2IVKCMxlqvs9TftKTnpzwYeWcNQ0ppm+byXoauouEL5l4d0BX44=,iv:4U/Q718J5bygg3DOWx67iKtgzeWB9fy92lk7xCY2Rl0=,tag:L1YtP8p96L4DPMgYEmcR9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
