apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lxup/homelab.git
    targetRevision: main
    path: kubernetes/core/services/intel-gpu-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
