apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflare-api-token-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./cloudflare-api-token.sops.yaml
