apiVersion: ENC[AES256_GCM,data:qWM=,iv:oP+iW3Ggh3VJrpLCkvNqfd0lslw7Ykc/Di0hjOjwjYk=,tag:GWjZdqjkzoTnZqPun1qA/A==,type:str]
kind: ENC[AES256_GCM,data:kZu2a5zD,iv:aslqO/AcLeJTNtOeyEGNGPCOlKmRk/TdFkSec0UYclQ=,tag:pfk7xrz7PUWjJGgzxImfCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x+figkB2W6edyNCU3M5J,iv:mMMwNxwCK2AddB1jr0z2KbIpLAIUF1zZ89c6HKHwPR0=,tag:Nhqgf8X/JQTo1ZVoWlkMxg==,type:str]
    namespace: ENC[AES256_GCM,data:DngQcZzTT577,iv:olPnCJmBtKwTuO+EDC9pWAMIkLIvsx4Im11rDeneDsg=,tag:bLEdoESE72Zp9/DR6DIQ5w==,type:str]
stringData:
    STGUIUSER: ENC[AES256_GCM,data:QtR5MA==,iv:HybSP1iM04PW0Wj7j/AaMgR73tP354jMB9DbUjDWSLs=,tag:zRj3V6jZ4quifm5P+Sx3Tw==,type:str]
    STGUIPASSWORD: ENC[AES256_GCM,data:6fieaFw7Uno4CNvcxmHOmvJIu8YJmnB1,iv:J90/oF1cTVM+1SVhiwTxoxuVNr/hia3Ob8eYf65YgjE=,tag:FV0pQRS+CG64V7vLgqGTYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZEdublkwYWpNZWZ3cGVH
            cm03Y25SVUJ1VWxabUJrcVI3NkhKTjZIdm1zCnhOcHJaN1RHQzlxMDBrTE1UbGNr
            NkNLM0dzSkwrN0NTaXdZR2ZmT3pnOHMKLS0tIHp2YlA2bWdVazBFc1BOaFhKZlo0
            UmduR0ZQQnNsRi94WnpPTEZTSEdvdzgKTR2ok8GvkdYQtilTDREvoSrawNO/mMB6
            DYjTtgnkdM/bEOg8lxjs2r8ST+Nrat6c4OBumtrl00Yrm3ZIMncXnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T18:54:33Z"
    mac: ENC[AES256_GCM,data:V25yfjHFuU+BTIJEtZQ1WD7TZ/VhLAG7jNbmEgtgOzCv+CdN87J23l0+hK7MTcOfCVss+yoDkycC/u2uQWsRIotcBhb+QEMRrCGxpSkxjQj2whOvKYiF/2GpEgtFVqjUFiOHaGegpuKreoalHyBopZUbCJ13wPJRWvtlPn3/Xfc=,iv:XRwAFbIWrAHNA/bf77bJR3j0ki+fZAFVEo75zuqblXc=,tag:bA2gwCNCKFP7zosZv4AFoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
