#ENC[AES256_GCM,data:DE5Hoy5QmcLXmhQ8sWCMPEnHmvdxIFxZYMpW8Mw9fidJX9hwzGHIAur62mQBGPdUlXEoPg3Hdetoo5xHGmiMhtALSFk=,iv:fzo0qdJa7E8Qr/8bTiNasE6Mo4GdDuurodQQe9qMJlg=,tag:3yjqscJ5Z2WvHUsufmAayg==,type:comment]
#ENC[AES256_GCM,data:UXlIHllV2iqwvsdix2C4c7hLvaswp1thB5HQZcRZNJ9wFJozntNbVpIsPMABY8Gp8mjptQWF4nshG9PaDsD59ovnP+XeAsJ72Yirw7N1IoJEZE4=,iv:/e4xgCDab8aHMc3bj/U02iNL3mlHFG/gURqirdeScn0=,tag:d6vd2o/xtYEv3XxMGu22vA==,type:comment]
#
#ENC[AES256_GCM,data:2SPpFq7n/98vpI0U5c7nS4qRQFR4tEV/+wZSMwfVKgCwyOq5/Z+Jf7CvXzZBMDN6ZHdpVZMJm1CWFPrf36AffS2zGh6IWw==,iv:o1ruVG7uXRF+UUsS9Smq7qcBunumBQnEStme+SVJrDA=,tag:fDY41XYsyp6lKim88/5feQ==,type:comment]
#ENC[AES256_GCM,data:vO19Y95HzyTcgIQJwjBT1lFb56z6yE+64XKyoWt/9OlG5EpL4A6dZBxNLpnIY1fGSrZ9WPg+jc/s8X6ZdG60vuJy,iv:7+RlgHDp4yNPsubO+91Tq7+jXVa2h3mtI5hPgZMxiow=,tag:irjfyS066ns1iJm1jjvD9w==,type:comment]
#ENC[AES256_GCM,data:qWM768EbI/bzJQQQXW9uyygtXZAIIlD+t+qx7dQsOe0jXSS1Zs3baVG82hqGR25ER61h,iv:xCHFcjH99DGzS7b7mLbJosqW02NbL3l0koJQQFrEpiI=,tag:KrXCcHRea+9/diA7PZjSJg==,type:comment]
#ENC[AES256_GCM,data:eZGmwm0Xzmikd2qLKqvKXsUoVVbrtTwj2eLc9suny89UknaA/50XQzgOrGnRKnTkCXQc3StObg==,iv:snSPnsd/AYZM0XMNQdpPODfA/J9Ed4kHEudPUW1IzCE=,tag:RQmzVw9nVB9muKVq8aaNfg==,type:comment]
#ENC[AES256_GCM,data:NztRoedgpCCE+CxtXhw2pn1BvTo0gj8uEgb231QdBdxuMb1Rrn9i4jsfIPj6ER5lmoALEPYAEkCECrDsBo9wLRjyzbOXR5Fj,iv:iaVXopOe2kAUxqM0EwT+6KTeVb90CqXZdX3bb/tlNFw=,tag:wmFh5KrpXV2frzX9Wejj7w==,type:comment]
#ENC[AES256_GCM,data:PqqW0EqBPcPlyx2+ThouiIdPeFY9rN6Xs8B/ZXEDJxPhgCy2BR1Cr6TTFjiR,iv:cJfXZGPM7rs2QtC5sK6abrY4/7XI2iTAp6XOpFnH9Xk=,tag:ndCq1O94sKFiOHlDkJTJpA==,type:comment]
#ENC[AES256_GCM,data:4EJPIie10w9Ojpga2L6ett+MAv7YMEdvb3SRggxdn5WGEWYACLDCy7bgONm2scqeLnMG5nMs90N8Uq36V9pnP6gwhHV0p8kFXw==,iv:g/OftPZxBQAjCVyI01avEgOQlOAVJjZiWGGLRPfJifM=,tag:RVPHKDSSFO3P8yBlYCrLgg==,type:comment]
apiVersion: ENC[AES256_GCM,data:qIc=,iv:7w2Qy72QUu/4lYCbr+1PZOvk2IoXruaUtfK75I/tFWA=,tag:CQRm4B1iRCZlzH0rcnoRlg==,type:str]
kind: ENC[AES256_GCM,data:QyD2tDtB,iv:AfnhA+VD+nWKgW+tP19qvW/5+l1+VSJAgNccVspvHyE=,tag:hbM0CEkH+pSIgk1drr8MPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Re2sFus4FMnA9IOFNxoaYQLddvvNw==,iv:fgr7UCu1YNhN8lIbzX2tw3mKMvqdkn43Ah4Fq01RB9g=,tag:sWUb/LmwKYwLhwXffV+rXA==,type:str]
    namespace: ENC[AES256_GCM,data:k2815DDEkA5u8W1iQerk,iv:xyEJLo2DiJQYO2WU/HdvzmF+O6QO9ElZnnEDppiA3Nk=,tag:GNsbzvcmJ4v0Qh4yn4ZddQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:P8jFLf8D/0MX3z/iLF5UkMCw7diLZy8u2l/0K9I9hqE=,iv:M4oI6seLt/XT6ztbyyYyz5fg5bhav15Wuc5LGNahkSI=,tag:VFPh7hh90iz7QASbHRBcmA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Np0HXGLGWj64mkc+zbjvyMJDYYerfaxTPImWkRNGgJ0QOXyPkvJ5IACWe+8ZLH+qCKyGXpkTq8KgCLjg9ZHULw==,iv:vvoAq2MNQ0VzjkxfPUHVY5ret5eiGg05eSYuj/u/6Gs=,tag:wPKe83oEV13t63U9FZiTiQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:SahWEGjRGVwl9gkg/4OeZQNegBUd2RqZ6y3+73Hh4z/2h91j8TgVaS9R9kRyg9y5cAwv2xCEeGG0JvibuK8bqdQ=,iv:78Fe6JO/0EM7SRTky9CJ3gB7nIa9Si7TUdteeGgIPuE=,tag:XUqcQptz8pul1L0eQ5J5kw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWFhKL2ZZNUE2V3pzTVZy
            b2VpMjdBVi84VWQyWGs4ZEg2VEFYdnVyN2pjCjFpL1JWdW9BaEtIVVdJUTR1Rjc3
            T1VJR3lDNGg1aTBpaVhQeDhDQWpMMlUKLS0tIFRPMkJsZlppakt0WEs4ZEFSOVps
            czNpRTU0eDVHd0FPLzhQajN1T3BZSVkKQW9NBVvtZsIbGgwwIjQMrxaWCJxr0fpS
            SQU7oPfm7VbIcOZBxLJIKe3IyCRNwQm4Rt/5F7rtYFgOUXFZ4wxLXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-02T19:59:09Z"
    mac: ENC[AES256_GCM,data:EfJsUWocetwBG2Fu86cSjzEbEKsZ9brDk2RrZOmToJFOUHAIZ+mD1Sww+fcaV4xHSR36ai/yG9tsqz7lDit4zbccFWxLHgiNNZ0ZUB6KFq55lJO6eIaRsWlcR+uguMwBRECs1nwUflHb4NB+UoTmxkiX/Wer5tvOgKx7Izqf1ps=,iv:cRopt1A/qujIfMMCMa2ihnLRYiTiXD31lLwUXcgkurk=,tag:YrwAKq73gWjBD6S0UlueJQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
