apiVersion: ENC[AES256_GCM,data:HRc=,iv:Ju2j1CH0Zo4BlT0drgV49W+rtBb07ytjzhtZOnPeowE=,tag:+pjPE2//Tv8gAPwWLOS/fQ==,type:str]
kind: ENC[AES256_GCM,data:V6frumxz,iv:DDLKLpsLKPFX9pjr65Hw3BNH6YsIjxxLfsy4+l72R5o=,tag:30+RsdbGM3djZD2YyAazMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mT2nKCtowfrL9u8N0RI=,iv:dAvAPJc4vx8SitSzB+rlrsjAlr1tk4+JXZ93eROb1qU=,tag:2jVsFIjgQPBesqV6Ri2Luw==,type:str]
    namespace: ENC[AES256_GCM,data:OVDxwErB,iv:ldI4H1hRDxj8otm6us5zTokJ0eGevuCQuHpBTztBQiY=,tag:YHAUv/qnAqLOAUFO4otSvg==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:iiouDT2w,iv:rGVOAtI06KN1EAvigiasonWoDdFjPYmxxXoXwqefrp4=,tag:PCp4DoejvFp/bXhIJ8KQ8A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Xiqt+BntBHvurpWdV7sc40BOSCVWU9XHZpL7AjMFgw==,iv:HpOFFt/0a8FGBJOH8hG15cOmAtOjJLVd/sJx3QX2ujw=,tag:blpfQdjVaFdAOWQdVehdLg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:u+RDenHd,iv:0BXL8hlhWUolozaXT500FIbHnkMePfy0Wrl+kZGBSYA=,tag:pZAKJqKgnX27tjzbIbNKuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKakREYzFDN2xLbm9oTGlJ
            OTUzRUVLbjJSTFBSazk5bm9iNTZxdXVKaUhFClgxSEhsblFwMVpPbmp1dkpaZ1c5
            emdXcXpmK29OMFVqMjJVaEk0b05EWmsKLS0tIFVNcFAxMHlRaWp1enNmd01vY1Iw
            L3FNWFlKUTlwSHdnV1EzTm9Qcy9hRFEKEPpYwyr+9wfoYMg09zb9Hlgu1vpxgkd1
            g83LMdCLBNt9Rrn12ePyWoGDNtbN3yn6VrF/ovClYbbf4874dTRujA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T01:04:01Z"
    mac: ENC[AES256_GCM,data:AGJYojDkXxaDrkyO/2tQKxFZ2gTSCN/46Jn8pzyE2zH1wjr+X9fjsUkAdl5G7sKXcibE0hfw7yy7TxOhOoEoiKE/qSI3lyLu87ivVE598TlnN2jEJ5Y6WsvqCJSGKSMHQRg5bbDcOgFPfx4C7jjy7GiT4cHPe5kD4qRnqwVfqYg=,iv:bca+So7mRspDXBe324ZnHzMEjTGZy//d78GM+u6HilA=,tag:zALLbTiI7G+y4zMoMiJW1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
