service:
  type: LoadBalancer

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    http:
      tls:
        enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true
