apiVersion: ENC[AES256_GCM,data:yzk=,iv:J/zUtOVBPY5BdiAiecxV1yz4cUPci8jNjgf//0McNvA=,tag:pcmbhnh4UCq8rFYDgJolOA==,type:str]
kind: ENC[AES256_GCM,data:7TuAlYef,iv:vWTBAvrJv5v4Bk1T+eezPlGZ0l+RpcH4AzJUc1OvHtE=,tag:xcAmR9fc4yLdltHzxMT9Aw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JGMt0dQUSz7u3LaJkR1NcNgM,iv:Z2R4VsVYD2Qgl/gOlAm3C1IkItTBDmrLRVCsxWxjfj4=,tag:RmzPw7DzNLr+Lq/nBPUf6g==,type:str]
    namespace: ENC[AES256_GCM,data:AaykruW2,iv:HV7PtiURCTSuVFa1HoaLTGmwQbvawtWK4xfPj3LqHqo=,tag:L2hGJP02+DV8M1hxeXjmXQ==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:2ViOeYtJYhP96g==,iv:L+EBIXUX2NseeNP45zlBmK7YthfNrmptRznt+gUf2s0=,tag:3UV/42Dm30bMjDHui9XhMw==,type:str]
stringData:
    type: ENC[AES256_GCM,data:tAuo,iv:iv2foUEMrgYtU+sMg48UR4zM6HP2tuYYNXvVnelSC5c=,tag:uJnLorn9fIE01cTdnBELqA==,type:str]
    url: ENC[AES256_GCM,data:uIQJxmy7xLwJsz0uwRj8rW9naKq34zXFooimRpUYJxRJz2g=,iv:wrniZsPWttPyvR08qR3QXnzFRlDvxkBSQMxJnqeyy24=,tag:7RVGI2PT7F81g/OrEeWaoQ==,type:str]
    username: ENC[AES256_GCM,data:mXLLbw==,iv:POGDqodkvPZm/iVDivVkpGnxIWMGF+hPCH/SmXXkA7E=,tag:94CNg3y3Mfoq7J02olvR6w==,type:str]
    password: ENC[AES256_GCM,data:8DNcv7k4xojZP25PJ48E8zd+cuz5WCWKjnXWMqsuhubP5MJRhi4pSG4ywOXhKGnmD57TSQAJ6kpSIswlx9bxxRiMuaOp/ACrUozHjeZOjV+vKHoAZnchgf4yEdKE,iv:JxqQu8s5smyxKR2ymp1a5e0uLtDpPPi28BhRxeRxJ9Y=,tag:vamZBriPHjGr84hSxJnHtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcmNybzJsS0JBRnE4NVdq
            SG1TV3hQNzVtc052R0s0QS9xMlNGZXUzeTNRCmpSSFhtMFRkSVFQUmFQektPUFZQ
            dUJsWXN0RXBxNTZhMG1NeEVNa0FTQW8KLS0tIFRzZWkxNXZDekZLN3laTVpKUHpp
            WmIxWGFqQUxIMXhoY0FyWHdIb09UTUEKySjN2EoOOQLS8mM1xpM8pzYinje9Feix
            w9hqq3Bf+j9Z1IxZrQCZ9OLdf4trtNeAH+wsRyWpJz0FnrtED1Os7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T10:18:01Z"
    mac: ENC[AES256_GCM,data:rWDZJN6cADMDPjyfBuKFPBzcVJ3w0TUrZhyekToJ2XdO0DZcZo47gVJjgZZ7PgMi8IfBrptVRzuKoq4L17g/mczpDfKmcWS16dRRzvNTJGv3R/SYOCaDRZPW86Q45vHFrQX0wY+OGtsima6YbOEOfP0vB+PS6u+GrxCyQtd1PrQ=,iv:veu1pM6Wecs4BtsCUPGpkWMsJAkBAmYJrci/GHb79gQ=,tag:k/wt74AJUl4EDW+55FKefg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
