apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nas-passthrough
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lxup/homelab.git
    targetRevision: main
    path: kubernetes/apps/services/nas-passthrough
  destination:
    server: https://kubernetes.default.svc
    namespace: nas-passthrough
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
