apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lxup/homelab.git
    targetRevision: main
    path: kubernetes/apps/services/syncthing
  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
