apiVersion: ENC[AES256_GCM,data:p7o=,iv:/Af4YWD62mtAdi3+dN6bel5EAFu163HIsLTTAf81n3s=,tag:iqD2g/wzYP/C4zZjBfPEKw==,type:str]
kind: ENC[AES256_GCM,data:+LUni/+d,iv:iQ9i+h/HrPaAEwgNVz7g3vyeVn1PJlqMPyogIsbIkPA=,tag:BZGIsK6/bhefziZPt25wWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FHvPPoRye+OV3Q==,iv:vESJwScd7Ggurenowfqqjtsh1mgEVMXzpy5+UxY2dFw=,tag:EbuSih3MXBTBsXrfFuiUkQ==,type:str]
    namespace: ENC[AES256_GCM,data:XkHeqTcxxwyR,iv:CigREg110nhjmInn6d3IsCusX1vZytu3qH6wg/HqXmE=,tag:1JxEKnMmMCTXJflhJaxH6w==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:OxWW73hVIq/bFwUWUEnQGnBORknO6gXc4pUIETcD0Frrd1QC2BbLjKscOse3nBVw1XIjIZzTmhMrAnWuDudP2etvUIDLypku40AxpXaVsmBfi4lCZuA=,iv:29NwYVP1l92oqr7H4+1HgXGERdmsYSkaYJIuZ/VJE20=,tag:oGgm1SsMoQJ9YGgR35065g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcmMyNnpHRXRuMFRxZEVD
            djBEUmJlME4wZUhrWHhnRDIveGtGUThkWWgwClcxa3F5OGowRmJaeFpYLzc2dUQz
            MzNRd1ZrTURtc1lxaWliZGtrbHFJeGsKLS0tIEhaMW5yaUduc2RGc1gxWVg4by9I
            eG9zbFNzSG45VEpORUgrU0gvRUg1MmcKfLh4/lmRSEBmfiLC0COUu2eaTO65KrKn
            93kKiymYoiyYMFpHGsuHp2Oyti4TCj7lxlLgkoexChkyGVQRbvBEyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T15:23:27Z"
    mac: ENC[AES256_GCM,data:dexcSEaltLjlaFgoXQ3jyy7u8mXXtiQvGuQ4la5CqT2vO5cT7rmIEmmQrU1SBE/fEVBN4sEkfbbDh1w+sj00fuuA1HBeUKB4QqDYacXr9+NkE5zaQXP2JYXGMPfGrAp9Smua8aIiSUuX0hIp6dSa1/6iUA6+k9nkhjpEjq6dc60=,iv:CUkrSJLKFqubOazQlvwB1rcwxGyitjrCMIi6x8QhC3c=,tag:kMAyUUPr8ujshFpZDUqoZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
