apiVersion: ENC[AES256_GCM,data:jVA=,iv:mXHtvw8LSpy0PUmdwDD1hJAl4sNub5DXGdJ4P6GN8KY=,tag:HKTLUhYqI4VCZmN74ZpbHg==,type:str]
kind: ENC[AES256_GCM,data:lwBHMG+N,iv:cVzwa1cjhFlEMRKs+ACsS934+N+5fzi2yQKuTNu2gCs=,tag:7+peAp3VUQUduxbYfK+rBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aPJ4491MS3OGVuZFEAk=,iv:8Dbt/yRaFbgmCLg6y8jAwAuNnRGnUVgSEQoZgfiUKl8=,tag:peSz6005lf993Eu6qyKvqQ==,type:str]
    namespace: ENC[AES256_GCM,data:0mJlczE113Bx,iv:5si0kWY5hRBKveMh5mYksC5cpzDYI1QWRPzMm6Otaoo=,tag:uX7F873+Li7UhUFGfCo8kA==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:mS8iV7SQp3EW,iv:Y9GybC4dK9i6UENCRYHP3CaD4+kRUTnlDlFHWY80ocE=,tag:RLxFp7ZtV54bfvDu5T0B3Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VGjLzxdhzkYOlYusdOsRv/Bs3zJNWAC8p303VzhGuQ==,iv:3dxUEn2Ip7RcpOnOqCVURVJ5Fj9JWMmK2c48qIRnCsA=,tag:lQuxfCja5jd7jVlgqlwllA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Ke1pPULC4Rj3,iv:+03ToLwN9Gn50ghZS//kD5lNsQE4h4/1KiF3CsulL1Q=,tag:eNr1xNSF1mY26Fsg49p3IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaE1yRi91bFU0aWpnVFpD
            eEZPMTIzVFpwWEpJUmZ5dnZDcDRLVjJvR2lFClMwYWdpL21CaFVtK2JWMGpYc2Fq
            MGttdHlleTJNV0h3clU5NUNoTHVodE0KLS0tIEdlQnBaRlo1RDJoT0Q0cDdKQnlZ
            WlRETDd1MTR3c1k4MnpaOWN3TjVrbzAKDpobfhA7c2W1i20V3clIPHvzWupnd18T
            G8Ag2dx2T+OZvz9HdEgi9abq7iACB032o+TSyMgc2fnS7aaQ4AUk5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-03T15:23:27Z"
    mac: ENC[AES256_GCM,data:YH0ypVc47p3H9Mft2LJq0DFCGG2ttqqK4SWj4WRY9Bap6hZCiVaTGAQfohXWE8+LjwCWNKlW4NGl+QENiKTuGtSCoiEmYEcD5Z5NVXBKh/tpCTLgBpQuExACQQWB/0K2QhJ1nd2CRtoAI4ri3v13LLr2vOqB0T236o2ccbu1zkg=,iv:pZHcX5PSUknb8byNVMSryI2DYj+VZe9gfjzGFiFaSfo=,tag:l9yVlqSrIgfSxAISL7+krQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
