#ENC[AES256_GCM,data:CYh6U3kKrEKgBes2h7/qDIetlh7AQUdFrpD/oOV7ekxJyQ+qd1Emc27B8kExvLPtmwhXQdjjpJN5ooUwJw==,iv:+lTt+yKPIjJ/AQhuzMVHfGs4UP4eZ3Y92d2SnfwfMEo=,tag:F6RP9EXhK3wR8fMDXJqElg==,type:comment]
#ENC[AES256_GCM,data:pDkQnLqmngSZr3WKQuJNAOPelv3EnKphZT4PI/pqlQ+kSaTf7CHQkZhjCNyVcEjn6g8WE6VT/u8K2SlOglDJ2Zj0DLTA/QyS618S2D9qiHG0ZOZi,iv:2zwy0sCpTn4vn46TIrBIG0Xh3RrsgMvhelnEOY7iM6s=,tag:1u1mGZgubbjjnmw95tKMHw==,type:comment]
#
#ENC[AES256_GCM,data:EX9+eyBId73bDIAvfL1nJH5vBzKCStMGFawXtwHqdlRt25ZtYuw0cCHj8yMdp/COBWvw3QipzSAibhCQQ5EK3A61WapGJmb7IA==,iv:zMyotN7K4SPcyHqoqqJL4UtIXT/8JLacSr5AajG7rbw=,tag:jEcN3aAPkOvWkApFXxPcaw==,type:comment]
#ENC[AES256_GCM,data:xk1Twbx9vYSGctNtk/1YAEkQPIGDEXmF+/iuHn2RY0QekJYNwhm17GMXmgFYWvL6j+ip1kcik15bd+cPrLPt9Mq+EDU9D/jb94IYwg==,iv:1fWWOOmVXTiED6RgEM/smGbX87ZJqh6O8bANZWFdSAc=,tag:jlwr6bArIxVVJAGP0bQbiQ==,type:comment]
#ENC[AES256_GCM,data:+GAAgAbnRz6Q+oOPP+NximOB/7GkZ1pY5lIouOdLJX8lfWLke75ruVX0ohNrvr+0sP16eQG0agYIrhRR,iv:Z0NZtC5ajADuPpxF84g3OrfkC52B5HZwLPxqRWAkeAk=,tag:qcPYWdF78ndPQqegzE+eEQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:P/k=,iv:wYbkAxbrXckU8Ubk1/YLCQVeqjD4Crly4+dgBtxxuGM=,tag:OEff19undWacPv1wSN5Ctw==,type:str]
kind: ENC[AES256_GCM,data:FrKwR4a4,iv:lugPun6lRQiYMZIyi5Q83RQjNRqGkW0heG7WucXMaq8=,tag:YWl4FHFYKtWUQfEuTCVE9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:undXiFKvFPrnea8tZfJ1dQ==,iv:o/f3msBsaIaRJT8N5Abkwb0fbR5yguysv4latGeleJs=,tag:WsCZVsVqARkbYsntbr4QYA==,type:str]
    namespace: ENC[AES256_GCM,data:L3ceh5v905Ecch48lGEu6OPWo2ts,iv:5n7BVha8fdCrHyoflJpCQ5SPfr8lcoF/drr3pwxtFeE=,tag:AJuqndC6NKKbz48JpWraZA==,type:str]
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:ua1GZsYf4Wzoo7o4u40RIebazlvLqkBVgOIK47+ztsY=,iv:4IegERmjX+8m7jubvAv+a48/4zx0NftYW+QIjLt0NRg=,tag:oAct5fm8K4Fba30VMWBb5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbUdGZGU2TXhmQkJCbExu
            YzVIWVcrbEdRRzA1bUdkN2JTRVlHQkVTeWwwCjF0a2dzMmIyZi9ENjZGWWwvK21k
            TE1DYndrTzJvTm55RjY0VG5BOEU4R3MKLS0tIHVXOVlpUUdaZlc2WjZqeDdpSDBp
            N3dCRmZoUUVzd3dtSEhpM1RFQzYvRU0KA1O3CgycJedqwNsO9Svq0+S+WCrQdZSw
            WZCYgqBA9jUYlFLlU2CADiqog1eA6+gRPWNEdqNZ8G0xpYFwdC/FEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xze49rtd29dpev58l3lsddpm986nk2vxh7pg4u7sy06rtnt82upszgkx5r
    lastmodified: "2026-10-02T19:36:06Z"
    mac: ENC[AES256_GCM,data:qUa6Zj300U6XqRJN0Zx+OLPLqyq3GRslnde/l+G7VKKfpnOq2qnMlN2yeI1KOB7W9n4/OaajWcwDZoaXyIYD6XXyEwAuTJvqpZTlpXYjKzsBuH7IaDcQvmHnvFuQu2X5amZm877WOZdVoNnw6CPFwlsr+bD7rjIS0OE2EoV9GDQ=,iv:idnugw14rNRldRoX1ow71hyf48t3oLvRypnhn+WbEgw=,tag:HfFtFYHMasQQmMMHhrUxbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
